services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.10.1-full
    ports:
      - "5001:5001"
    depends_on:
      - database
      - minio
    environment:
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: miniopass
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5001
      --serve-artifacts
      --backend-store-uri postgresql+psycopg2://mlflow:mlflow@database:5432/mlflow_db
      --default-artifact-root s3://mlflow/
      --allowed-hosts '*'
      --cors-allowed-origins '*'
    restart: always

  database:
    image: postgres:18-alpine3.23
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniopass
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: always

  minio-setup:
    image: quay.io/minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10 &&
      mc alias set minio http://minio:9000 minio miniopass &&
      mc mb minio/mlflow --ignore-existing
      "

volumes:
  pgdata: {}
  minio_data: {}
